Language: zh_CN
#######################
####常规设置(Normal)####
#######################
##玩家首次登入时的礼物 将会读取giftPack.yml内的物品 如果不给礼物则输入null
PlayerFirstJoinGift: NewbiePack
##玩家登入登出行为消息
PlayerFirstJoinMessage: "Welcome New Player Join Server"
PlayerJoinMessage: "§f[§a+§f] %player_name%"
PlayerQuitMessage: "§f[§c-§f] %player_name%"
####################################
####多人服务器列表展示 (ServerList)####
####################################
##服务器列表里服务器展示的文字
##最多只支持2行文字 多出部分不显示
MOTD:
  - "§3§lNew §b§lServer §f§l[1.20]"
  - "§3§l§m       §b§l§m       §f§l§m       §r    §4§lSupported §c§lBy §f§lPoPlugin"
##服务器列表里服务器展示的图标
##将图片文件放在插件文件夹中 ServerIcon填入文件名[要带后缀]
##图片文件像素大小必须是16的倍数且是正方形 建议64x64
ServerIcon: "Icon.png"
##服务器列表里服务器展示的最大人数
##仅展示用 并不影响实际服务器设置的最大人数限制
MaxPlayerDisplay: 100000
###################################
####自定义物品 (CustomItemStack)####
###################################
##将要读取的物品文件
##文件需在文件夹itemStack内存放
ItemFileInLoad:
  - example.yml